archives:
  - files:
      - none*
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
before:
  hooks:
    - 'go mod download'
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X main.Version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
checksum:
  algorithm: sha256
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
# publishers:
#   - checksum: true
#     cmd: hc-releases upload-file {{ abs .ArtifactPath }}
#     env:
#       - AWS_ACCESS_KEY_ID={{ .Env.AWS_ACCESS_KEY_ID }}
#       - AWS_SECRET_ACCESS_KEY={{ .Env.AWS_SECRET_ACCESS_KEY }}
#       - AWS_SESSION_TOKEN={{ .Env.AWS_SESSION_TOKEN }}
#     name: hc-releases
#     signature: true
release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  # ids:
  #   - none
signs:
  - args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
    artifacts: checksum
  # - args: ["sign", "--dearmor", "--file", "${artifact}", "--out", "${signature}"]
  #   artifacts: checksum
  #   cmd: signore
  #   signature: ${artifact}.72D7468F.sig
snapshot:
  name_template: "{{ .Tag }}-next"
