name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  go-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: go-version
        run: echo "::set-output name=version::$(cat ./.go-version)"
  terraform-provider-release:
    name: 'Terraform Provider Release'
    uses: bflad/ghaction-terraform-provider-release/.github/workflows/community.yml@main
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
    with:
      setup-go-version: '${{ needs.go-version.outputs.version }}'
      terraform-registry-manifest-source: 'terraform-registry-manifest.json'
